server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:Han#222@47.100.77.11:27017
      #uri:  mongodb://test:root@129.211.15.108:27017
      #uri:  mongodb://root:123@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 47.100.77.11
    port: 5672
    username: han
    password: Han#222
    virtualHost: /
xuecheng:
  mq:
    queue: queue_cms_postpage_02
    routingKey: 5a751fab6abb5044e0d19ea1