server:
  port: 8088
spring:
  application:
    name: test-freemarker
  data:
    mongodb:
        uri:  mongodb://root:Han#222@47.100.77.11:27017
      #uri:  mongodb://test:root@129.211.15.108:27017
      #uri:  mongodb://root:123@localhost:27017
        database: xc_cms
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
